// <auto-generated />
using System;
using Kairudev.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kairudev.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KairudevDbContext))]
    [Migration("20260224131351_AddPomodoro")]
    partial class AddPomodoro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Kairudev.Domain.Pomodoro.PomodoroSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("LinkedTaskIdValues")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LinkedTaskIds");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PomodoroSessions", (string)null);
                });

            modelBuilder.Entity("Kairudev.Domain.Tasks.DeveloperTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Kairudev.Infrastructure.Persistence.Internal.PomodoroSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongBreakDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortBreakDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SprintDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PomodoroSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
